### ISSUE TITLE
I'm unable to run the development server on my localhost

### ISSUE THREAD

**Issue by CodeWizarz** [studio-freight/sf-website#9]
in my local machine i used yarn package manager to install dependencies and run it but i caught up with an error 
## TypeError: Cannot read properties of undefined (reading 'studioFreight')
# > 246 | const [{ studioFreight }, { footer }, { contact }, { projectList }] =

i dont know if its related to graphql.

**Comment by GFier** [comment]
Hi! 

We are using [Contentful](https://www.contentful.com/) for headless CMS.  As you see all the data is being pulled through graphQL in the getStaticProps. You get the error because you don't have the credentials to request the data. You will have to create your own Contentful space and use your credentials to pull your data. 

Or if you just want to do a fast test, you can remove the graphQL queries and replace them with mock data.

Hope it helps!

**Comment by CodeWizarz** [comment]
@GFier Hey thank you for clearing up the clouds. I had a hunch that it was pulling data from the team's graphql.
